package api

// Medicines in common use in Mexico, by generic name. Doses are typical adult/pediatric references only.
// Control: "Antibiótico" (receta retenida), "Fracción III" (receta retenida), "Fracción I o II" (cannot be issued here).
func humanMeds() []catMed {
	const (
		analg  = "Analgésico / antipirético"
		aine   = "AINE"
		abx    = "Antibiótico"
		antih  = "Antihistamínico"
		gi     = "Gastrointestinal"
		resp   = "Respiratorio"
		cort   = "Corticoide"
		antip  = "Antiparasitario"
		antim  = "Antimicótico"
		antiv  = "Antiviral"
		cardio = "Cardiovascular"
		diab   = "Antidiabético"
		lipid  = "Hipolipemiante"
		neuro  = "Neurología"
		psi    = "Psiquiatría"
		horm   = "Hormonal"
		vit    = "Vitaminas y suplementos"
		topic  = "Dermatología (tópico)"
		oft    = "Oftalmología"
		oto    = "Otología"
		musc   = "Relajante muscular"
		uro    = "Urología"
		anest  = "Anestésico local"
		no     = "No"
	)
	return []catMed{
		// Analgésicos y antipiréticos
		med("Paracetamol", analg, no, "Oral", "500 mg a 1 g cada 6-8 h; máx. 4 g/día", "Tabletas 500 mg", "Tabletas 750 mg", "Solución en gotas 100 mg/mL", "Suspensión 160 mg/5 mL").
			kg(12.5, 75).conc("Gotas 100 mg/mL", 100).conc("Suspensión 160 mg/5 mL", 32).note("Pediátrico: 10-15 mg/kg por toma cada 4-6 h."),
		med("Metamizol sódico", analg, no, "Oral", "500 mg a 1 g cada 6-8 h", "Tabletas 500 mg", "Ampolleta 1 g/2 mL", "Solución en gotas 500 mg/mL"),
		med("Ácido acetilsalicílico", aine, no, "Oral", "Analgésico 500 mg cada 6-8 h; antiagregante 100 mg al día", "Tabletas 100 mg", "Tabletas 500 mg").note("Evitar en menores de 16 años con fiebre (síndrome de Reye)."),
		med("Tramadol", analg, "Fracción III", "Oral", "50 mg cada 8 h", "Cápsulas 50 mg", "Solución en gotas 100 mg/mL", "Ampolleta 100 mg/2 mL"),
		med("Tramadol / paracetamol", analg, "Fracción III", "Oral", "1 tableta cada 8 h", "Tabletas 37.5 mg/325 mg"),
		// AINE
		med("Ibuprofeno", aine, no, "Oral", "400 mg cada 8 h con alimentos", "Tabletas 400 mg", "Tabletas 600 mg", "Suspensión 100 mg/5 mL", "Suspensión 200 mg/5 mL").
			kg(7.5, 40).conc("Suspensión 100 mg/5 mL", 20).conc("Suspensión 200 mg/5 mL", 40).note("Pediátrico: 5-10 mg/kg por toma cada 6-8 h."),
		med("Naproxeno", aine, no, "Oral", "250 a 500 mg cada 12 h", "Tabletas 250 mg", "Tabletas 500 mg", "Suspensión 125 mg/5 mL").
			kg(6, 20).conc("Suspensión 125 mg/5 mL", 25),
		med("Naproxeno sódico", aine, no, "Oral", "275 a 550 mg cada 12 h", "Tabletas 275 mg", "Tabletas 550 mg"),
		med("Diclofenaco", aine, no, "Oral", "50 mg cada 8-12 h con alimentos", "Tabletas 50 mg", "Cápsulas 100 mg liberación prolongada", "Ampolleta 75 mg/3 mL").kg(1, 3),
		med("Ketorolaco", aine, no, "Oral", "10 mg cada 6-8 h; máx. 5 días", "Tabletas 10 mg", "Tabletas sublinguales 30 mg", "Ampolleta 30 mg/mL"),
		med("Meloxicam", aine, no, "Oral", "7.5 a 15 mg una vez al día", "Tabletas 7.5 mg", "Tabletas 15 mg"),
		med("Piroxicam", aine, no, "Oral", "20 mg una vez al día", "Cápsulas 20 mg"),
		med("Indometacina", aine, no, "Oral", "25 mg cada 8-12 h con alimentos", "Cápsulas 25 mg"),
		med("Celecoxib", aine, no, "Oral", "100 a 200 mg cada 12 h", "Cápsulas 100 mg", "Cápsulas 200 mg"),
		med("Etoricoxib", aine, no, "Oral", "60 a 120 mg una vez al día", "Tabletas 60 mg", "Tabletas 90 mg", "Tabletas 120 mg"),
		med("Nimesulida", aine, no, "Oral", "100 mg cada 12 h", "Tabletas 100 mg"),
		med("Dexketoprofeno", aine, no, "Oral", "25 mg cada 8 h", "Tabletas 25 mg"),
		// Antibióticos
		med("Amoxicilina", abx, "Antibiótico", "Oral", "500 mg cada 8 h", "Cápsulas 500 mg", "Tabletas 500 mg", "Suspensión 250 mg/5 mL", "Suspensión 500 mg/5 mL").
			kg(15, 90).conc("Suspensión 250 mg/5 mL", 50).conc("Suspensión 500 mg/5 mL", 100).note("Pediátrico: 25-50 mg/kg/día divididos cada 8 h (hasta 90 mg/kg/día en dosis altas cada 12 h)."),
		med("Amoxicilina / ácido clavulánico", abx, "Antibiótico", "Oral", "875/125 mg cada 12 h", "Tabletas 500/125 mg", "Tabletas 875/125 mg", "Suspensión 250/62.5 mg por 5 mL", "Suspensión 400/57 mg por 5 mL").
			kg(20, 90).conc("Suspensión 250/62.5 mg por 5 mL (amoxicilina)", 50).conc("Suspensión 400/57 mg por 5 mL (amoxicilina)", 80).note("Las dosis en mg/kg se refieren al componente amoxicilina."),
		med("Ampicilina", abx, "Antibiótico", "Oral", "500 mg cada 6 h", "Cápsulas 500 mg", "Frasco ámpula 500 mg", "Frasco ámpula 1 g"),
		med("Dicloxacilina", abx, "Antibiótico", "Oral", "500 mg cada 6 h", "Cápsulas 500 mg", "Suspensión 250 mg/5 mL").kg(12.5, 100).conc("Suspensión 250 mg/5 mL", 50),
		med("Penicilina G benzatínica", abx, "Antibiótico", "Intramuscular", "1,200,000 UI dosis única (faringitis estreptocócica)", "Frasco ámpula 1,200,000 UI"),
		med("Penicilina G procaínica", abx, "Antibiótico", "Intramuscular", "600,000 a 1,200,000 UI cada 24 h", "Frasco ámpula 400,000 UI"),
		med("Cefalexina", abx, "Antibiótico", "Oral", "500 mg cada 6 h", "Cápsulas 500 mg", "Tabletas 500 mg", "Suspensión 250 mg/5 mL").kg(12.5, 100).conc("Suspensión 250 mg/5 mL", 50),
		med("Cefadroxilo", abx, "Antibiótico", "Oral", "500 mg cada 12 h", "Cápsulas 500 mg", "Suspensión 250 mg/5 mL").kg(15, 50).conc("Suspensión 250 mg/5 mL", 50),
		med("Cefuroxima", abx, "Antibiótico", "Oral", "250 a 500 mg cada 12 h", "Tabletas 250 mg", "Tabletas 500 mg", "Suspensión 250 mg/5 mL").kg(15, 30).conc("Suspensión 250 mg/5 mL", 50),
		med("Cefixima", abx, "Antibiótico", "Oral", "400 mg una vez al día", "Cápsulas 400 mg", "Suspensión 100 mg/5 mL").kg(8, 8).conc("Suspensión 100 mg/5 mL", 20),
		med("Ceftriaxona", abx, "Antibiótico", "Intramuscular", "1 g cada 12-24 h", "Frasco ámpula 500 mg", "Frasco ámpula 1 g"),
		med("Azitromicina", abx, "Antibiótico", "Oral", "500 mg una vez al día por 3 días", "Tabletas 500 mg", "Suspensión 200 mg/5 mL").kg(10, 12).conc("Suspensión 200 mg/5 mL", 40),
		med("Claritromicina", abx, "Antibiótico", "Oral", "500 mg cada 12 h", "Tabletas 250 mg", "Tabletas 500 mg", "Suspensión 125 mg/5 mL", "Suspensión 250 mg/5 mL").kg(7.5, 15).conc("Suspensión 125 mg/5 mL", 25).conc("Suspensión 250 mg/5 mL", 50),
		med("Eritromicina", abx, "Antibiótico", "Oral", "500 mg cada 6 h", "Tabletas 500 mg", "Suspensión 250 mg/5 mL").kg(10, 50).conc("Suspensión 250 mg/5 mL", 50),
		med("Clindamicina", abx, "Antibiótico", "Oral", "300 mg cada 6-8 h", "Cápsulas 300 mg", "Ampolleta 300 mg/2 mL").kg(7.5, 40),
		med("Doxiciclina", abx, "Antibiótico", "Oral", "100 mg cada 12 h", "Tabletas 100 mg", "Cápsulas 100 mg").note("Evitar en embarazo y en menores de 8 años."),
		med("Ciprofloxacino", abx, "Antibiótico", "Oral", "500 mg cada 12 h", "Tabletas 250 mg", "Tabletas 500 mg"),
		med("Levofloxacino", abx, "Antibiótico", "Oral", "500 a 750 mg una vez al día", "Tabletas 500 mg", "Tabletas 750 mg"),
		med("Moxifloxacino", abx, "Antibiótico", "Oral", "400 mg una vez al día", "Tabletas 400 mg"),
		med("Trimetoprima / sulfametoxazol", abx, "Antibiótico", "Oral", "160/800 mg cada 12 h", "Tabletas 80/400 mg", "Tabletas 160/800 mg", "Suspensión 40/200 mg por 5 mL").
			kg(4, 12).conc("Suspensión 40/200 mg por 5 mL (trimetoprima)", 8).note("Las dosis en mg/kg se refieren al componente trimetoprima."),
		med("Metronidazol", abx, "Antibiótico", "Oral", "500 mg cada 8 h", "Tabletas 500 mg", "Óvulos 500 mg", "Suspensión 250 mg/5 mL").kg(7.5, 30).conc("Suspensión 250 mg/5 mL", 50),
		med("Tinidazol", abx, "Antibiótico", "Oral", "2 g dosis única", "Tabletas 500 mg"),
		med("Nitrofurantoína", abx, "Antibiótico", "Oral", "100 mg cada 6-12 h", "Cápsulas 100 mg"),
		med("Fosfomicina", abx, "Antibiótico", "Oral", "3 g dosis única", "Sobre 3 g"),
		med("Gentamicina", abx, "Antibiótico", "Intramuscular", "3 a 5 mg/kg/día", "Ampolleta 80 mg/2 mL"),
		med("Amikacina", abx, "Antibiótico", "Intramuscular", "15 mg/kg/día", "Ampolleta 100 mg/2 mL", "Ampolleta 500 mg/2 mL"),
		med("Vancomicina", abx, "Antibiótico", "Intravenosa", "15-20 mg/kg cada 8-12 h", "Frasco ámpula 500 mg"),
		// Antimicóticos, antivirales y antiparasitarios
		med("Fluconazol", antim, no, "Oral", "150 mg dosis única (candidiasis vaginal); 100-200 mg/día", "Cápsulas 100 mg", "Cápsulas 150 mg", "Suspensión 50 mg/5 mL").kg(4, 6).conc("Suspensión 50 mg/5 mL", 10),
		med("Ketoconazol", antim, no, "Oral", "200 mg una vez al día", "Tabletas 200 mg"),
		med("Terbinafina", antim, no, "Oral", "250 mg una vez al día", "Tabletas 250 mg"),
		med("Itraconazol", antim, no, "Oral", "100 a 200 mg una vez al día", "Cápsulas 100 mg"),
		med("Nistatina", antim, no, "Oral", "100,000 UI (1 mL) cada 6 h en cavidad oral", "Suspensión 100,000 UI/mL"),
		med("Clotrimazol", antim, no, "Tópica", "Aplicar 2 veces al día", "Crema 1%", "Óvulos 100 mg", "Óvulos 500 mg"),
		med("Miconazol", antim, no, "Tópica", "Aplicar 2 veces al día", "Crema 2%"),
		med("Aciclovir", antiv, no, "Oral", "400 mg cada 8 h (herpes); 800 mg cada 4 h (zóster)", "Tabletas 200 mg", "Tabletas 400 mg", "Tabletas 800 mg", "Suspensión 200 mg/5 mL", "Crema 5%").kg(20, 80).conc("Suspensión 200 mg/5 mL", 40),
		med("Valaciclovir", antiv, no, "Oral", "500 mg a 1 g cada 12 h", "Tabletas 500 mg"),
		med("Oseltamivir", antiv, no, "Oral", "75 mg cada 12 h por 5 días", "Cápsulas 75 mg"),
		med("Albendazol", antip, no, "Oral", "400 mg dosis única", "Tabletas 200 mg", "Tabletas 400 mg", "Suspensión"),
		med("Mebendazol", antip, no, "Oral", "100 mg cada 12 h por 3 días", "Tabletas 100 mg"),
		med("Nitazoxanida", antip, no, "Oral", "500 mg cada 12 h por 3 días", "Tabletas 500 mg", "Suspensión 100 mg/5 mL").kg(7.5, 15).conc("Suspensión 100 mg/5 mL", 20),
		med("Ivermectina", antip, no, "Oral", "200 mcg/kg dosis única", "Tabletas 6 mg").kg(0.2, 0.4),
		med("Praziquantel", antip, no, "Oral", "Según parasitosis (p. ej. 5-10 mg/kg dosis única)", "Tabletas 600 mg"),
		med("Secnidazol", antip, no, "Oral", "2 g dosis única", "Tabletas 500 mg", "Suspensión"),
		med("Permetrina", antip, no, "Tópica", "Aplicar y enjuagar a las 8-12 h; repetir en 7 días", "Loción 1%", "Crema 5%"),
		// Antihistamínicos
		med("Loratadina", antih, no, "Oral", "10 mg una vez al día", "Tabletas 10 mg", "Jarabe 5 mg/5 mL"),
		med("Cetirizina", antih, no, "Oral", "10 mg una vez al día", "Tabletas 10 mg", "Solución en gotas 10 mg/mL", "Jarabe 5 mg/5 mL"),
		med("Levocetirizina", antih, no, "Oral", "5 mg una vez al día", "Tabletas 5 mg"),
		med("Desloratadina", antih, no, "Oral", "5 mg una vez al día", "Tabletas 5 mg", "Jarabe 2.5 mg/5 mL"),
		med("Fexofenadina", antih, no, "Oral", "120 a 180 mg una vez al día", "Tabletas 120 mg", "Tabletas 180 mg"),
		med("Clorfenamina", antih, no, "Oral", "4 mg cada 6-8 h", "Tabletas 4 mg", "Jarabe 2 mg/5 mL"),
		med("Hidroxizina", antih, no, "Oral", "25 mg cada 6-8 h", "Tabletas 10 mg", "Tabletas 25 mg"),
		// Respiratorio
		med("Salbutamol", resp, no, "Inhalada", "100-200 mcg (1-2 inhalaciones) cada 4-6 h según necesidad", "Inhalador 100 mcg/dosis", "Jarabe 2 mg/5 mL", "Tabletas 2 mg", "Tabletas 4 mg").kg(0.1, 0.3).conc("Jarabe 2 mg/5 mL", 0.4),
		med("Bromuro de ipratropio", resp, no, "Inhalada", "2 inhalaciones cada 6-8 h", "Inhalador 20 mcg/dosis", "Solución para nebulizar 0.25 mg/mL"),
		med("Budesonida", resp, no, "Inhalada", "200-400 mcg cada 12 h", "Suspensión para nebulizar 0.25 mg/mL", "Suspensión para nebulizar 0.5 mg/mL", "Inhalador 200 mcg/dosis"),
		med("Beclometasona", resp, no, "Inhalada", "100-200 mcg cada 12 h", "Inhalador 50 mcg/dosis", "Inhalador 250 mcg/dosis"),
		med("Fluticasona", resp, no, "Nasal", "2 aplicaciones por fosa nasal al día", "Aerosol nasal 50 mcg/dosis"),
		med("Mometasona", resp, no, "Nasal", "2 aplicaciones por fosa nasal al día", "Aerosol nasal 50 mcg/dosis"),
		med("Montelukast", resp, no, "Oral", "10 mg al día por la noche (adultos); 5 mg 6-14 años; 4 mg 2-5 años", "Tabletas 10 mg", "Tabletas masticables 4 mg", "Tabletas masticables 5 mg"),
		med("Ambroxol", resp, no, "Oral", "30 mg cada 8 h", "Tabletas 30 mg", "Jarabe 15 mg/5 mL", "Jarabe 30 mg/5 mL", "Solución en gotas 7.5 mg/mL").kg(0.5, 1.6).conc("Jarabe 15 mg/5 mL", 3).conc("Jarabe 30 mg/5 mL", 6).conc("Gotas 7.5 mg/mL", 7.5),
		med("Acetilcisteína", resp, no, "Oral", "600 mg una vez al día o 200 mg cada 8 h", "Sobre 200 mg", "Tabletas efervescentes 600 mg"),
		med("Carbocisteína", resp, no, "Oral", "750 mg cada 8 h", "Jarabe 250 mg/5 mL", "Cápsulas 375 mg"),
		med("Dextrometorfano", resp, no, "Oral", "15-30 mg cada 6-8 h", "Jarabe 15 mg/5 mL"),
		med("Oximetazolina", resp, no, "Nasal", "2-3 gotas o 1-2 nebulizaciones cada 12 h, máx. 3 días", "Solución nasal 0.05%"),
		med("Cloruro de sodio solución nasal", resp, no, "Nasal", "Lavados nasales según necesidad", "Solución 0.9% nebulizador"),
		// Gastrointestinal
		med("Omeprazol", gi, no, "Oral", "20 mg una vez al día antes del desayuno", "Cápsulas 20 mg", "Cápsulas 40 mg"),
		med("Pantoprazol", gi, no, "Oral", "40 mg una vez al día antes del desayuno", "Tabletas 40 mg"),
		med("Esomeprazol", gi, no, "Oral", "20 a 40 mg una vez al día", "Tabletas 20 mg", "Tabletas 40 mg"),
		med("Lansoprazol", gi, no, "Oral", "30 mg una vez al día", "Cápsulas 30 mg"),
		med("Famotidina", gi, no, "Oral", "20 a 40 mg al acostarse", "Tabletas 20 mg", "Tabletas 40 mg"),
		med("Sucralfato", gi, no, "Oral", "1 g cada 6 h antes de alimentos", "Tabletas 1 g", "Suspensión 1 g/5 mL"),
		med("Hidróxido de aluminio / magnesio", gi, no, "Oral", "10-15 mL después de alimentos y al acostarse", "Suspensión oral"),
		med("Metoclopramida", gi, no, "Oral", "10 mg cada 8 h antes de alimentos; máx. 5 días", "Tabletas 10 mg", "Ampolleta 10 mg/2 mL", "Solución en gotas 4 mg/mL"),
		med("Ondansetrón", gi, no, "Oral", "4 a 8 mg cada 8-12 h", "Tabletas 4 mg", "Tabletas 8 mg", "Ampolleta 8 mg/4 mL").kg(0.15, 0.45),
		med("Domperidona", gi, no, "Oral", "10 mg cada 8 h antes de alimentos", "Tabletas 10 mg", "Suspensión 5 mg/5 mL").kg(0.25, 0.75).conc("Suspensión 5 mg/5 mL", 1),
		med("Butilhioscina", gi, no, "Oral", "10 mg cada 8 h", "Tabletas 10 mg", "Ampolleta 20 mg/mL"),
		med("Trimebutina", gi, no, "Oral", "200 mg cada 8 h antes de alimentos", "Tabletas 200 mg", "Suspensión 24 mg/5 mL"),
		med("Loperamida", gi, no, "Oral", "4 mg inicial y 2 mg tras cada evacuación; máx. 16 mg/día", "Tabletas 2 mg"),
		med("Racecadotrilo", gi, no, "Oral", "100 mg cada 8 h", "Cápsulas 100 mg", "Sobre 10 mg", "Sobre 30 mg").kg(1.5, 4.5),
		med("Simeticona", gi, no, "Oral", "40-125 mg después de alimentos", "Tabletas 125 mg", "Solución en gotas 100 mg/mL"),
		med("Lactulosa", gi, no, "Oral", "15-30 mL al día", "Solución 3.33 g/5 mL"),
		med("Polietilenglicol 3350", gi, no, "Oral", "17 g disueltos en agua una vez al día", "Sobre 17 g"),
		med("Bisacodilo", gi, no, "Oral", "5-10 mg al acostarse", "Tabletas 5 mg", "Supositorio 10 mg"),
		med("Saccharomyces boulardii", gi, no, "Oral", "250 mg cada 12 h", "Cápsulas 250 mg", "Sobre 250 mg"),
		med("Sales de rehidratación oral", gi, no, "Oral", "Tras cada evacuación líquida, a sorbos", "Sobre para 1 litro", "Solución lista para beber"),
		med("Mesalazina", gi, no, "Oral", "500 mg a 1 g cada 8 h", "Tabletas 500 mg"),
		// Corticoides
		med("Prednisona", cort, no, "Oral", "5 a 60 mg/día según indicación", "Tabletas 5 mg", "Tabletas 50 mg").kg(0.5, 2),
		med("Metilprednisolona", cort, no, "Oral", "4 a 48 mg/día según indicación", "Tabletas 4 mg", "Tabletas 8 mg", "Tabletas 16 mg", "Frasco ámpula 40 mg", "Frasco ámpula 500 mg"),
		med("Dexametasona", cort, no, "Oral", "0.5 a 8 mg/día según indicación", "Tabletas 0.5 mg", "Tabletas 4 mg", "Ampolleta 8 mg/2 mL", "Ampolleta 4 mg/mL"),
		med("Hidrocortisona", cort, no, "Intravenosa", "100 mg cada 6-8 h en urgencias", "Frasco ámpula 100 mg", "Crema 1%"),
		med("Deflazacort", cort, no, "Oral", "6 a 90 mg/día según indicación", "Tabletas 6 mg", "Tabletas 30 mg"),
		med("Betametasona", cort, no, "Tópica", "Aplicar capa fina 1-2 veces al día", "Crema 0.05%", "Ungüento 0.05%"),
		med("Clobetasol", cort, no, "Tópica", "Aplicar capa fina cada 12 h, máx. 2 semanas", "Crema 0.05%", "Ungüento 0.05%"),
		// Cardiovascular
		med("Losartán", cardio, no, "Oral", "50 a 100 mg una vez al día", "Tabletas 50 mg", "Tabletas 100 mg"),
		med("Telmisartán", cardio, no, "Oral", "40 a 80 mg una vez al día", "Tabletas 40 mg", "Tabletas 80 mg"),
		med("Valsartán", cardio, no, "Oral", "80 a 160 mg una vez al día", "Tabletas 80 mg", "Tabletas 160 mg"),
		med("Candesartán", cardio, no, "Oral", "8 a 16 mg una vez al día", "Tabletas 8 mg", "Tabletas 16 mg"),
		med("Enalapril", cardio, no, "Oral", "10 a 20 mg cada 12-24 h", "Tabletas 10 mg", "Tabletas 20 mg"),
		med("Captopril", cardio, no, "Oral", "25 a 50 mg cada 8-12 h", "Tabletas 25 mg", "Tabletas 50 mg"),
		med("Lisinopril", cardio, no, "Oral", "10 a 40 mg una vez al día", "Tabletas 10 mg", "Tabletas 20 mg"),
		med("Amlodipino", cardio, no, "Oral", "5 a 10 mg una vez al día", "Tabletas 5 mg", "Tabletas 10 mg"),
		med("Nifedipino", cardio, no, "Oral", "30 a 60 mg una vez al día (liberación prolongada)", "Tabletas 30 mg liberación prolongada"),
		med("Diltiazem", cardio, no, "Oral", "60 mg cada 8 h", "Tabletas 30 mg", "Tabletas 60 mg", "Cápsulas 90 mg liberación prolongada"),
		med("Metoprolol", cardio, no, "Oral", "50 a 100 mg cada 12 h", "Tabletas 50 mg", "Tabletas 100 mg"),
		med("Atenolol", cardio, no, "Oral", "50 a 100 mg una vez al día", "Tabletas 50 mg", "Tabletas 100 mg"),
		med("Bisoprolol", cardio, no, "Oral", "2.5 a 10 mg una vez al día", "Tabletas 5 mg", "Tabletas 10 mg"),
		med("Carvedilol", cardio, no, "Oral", "6.25 a 25 mg cada 12 h", "Tabletas 6.25 mg", "Tabletas 12.5 mg", "Tabletas 25 mg"),
		med("Propranolol", cardio, no, "Oral", "10 a 40 mg cada 8-12 h", "Tabletas 10 mg", "Tabletas 40 mg"),
		med("Hidroclorotiazida", cardio, no, "Oral", "12.5 a 25 mg una vez al día", "Tabletas 25 mg"),
		med("Clortalidona", cardio, no, "Oral", "12.5 a 25 mg una vez al día", "Tabletas 25 mg", "Tabletas 50 mg"),
		med("Furosemida", cardio, no, "Oral", "20 a 80 mg/día", "Tabletas 40 mg", "Ampolleta 20 mg/2 mL"),
		med("Espironolactona", cardio, no, "Oral", "25 a 100 mg/día", "Tabletas 25 mg", "Tabletas 100 mg"),
		med("Hidralazina", cardio, no, "Oral", "25 a 50 mg cada 8 h", "Tabletas 50 mg"),
		med("Metildopa", cardio, no, "Oral", "250 a 500 mg cada 8 h (hipertensión en el embarazo)", "Tabletas 250 mg", "Tabletas 500 mg"),
		med("Isosorbida dinitrato", cardio, no, "Sublingual", "5 mg sublingual en crisis; 10 mg cada 8 h", "Tabletas 5 mg", "Tabletas 10 mg"),
		med("Clopidogrel", cardio, no, "Oral", "75 mg una vez al día", "Tabletas 75 mg"),
		med("Warfarina", cardio, no, "Oral", "Individualizada según INR", "Tabletas 5 mg"),
		med("Apixabán", cardio, no, "Oral", "5 mg cada 12 h", "Tabletas 5 mg"),
		med("Rivaroxabán", cardio, no, "Oral", "20 mg una vez al día con alimentos", "Tabletas 15 mg", "Tabletas 20 mg"),
		med("Digoxina", cardio, no, "Oral", "0.125 a 0.25 mg una vez al día", "Tabletas 0.25 mg"),
		med("Amiodarona", cardio, no, "Oral", "200 mg una vez al día (mantenimiento)", "Tabletas 200 mg"),
		med("Atorvastatina", lipid, no, "Oral", "10 a 80 mg por la noche", "Tabletas 10 mg", "Tabletas 20 mg", "Tabletas 40 mg", "Tabletas 80 mg"),
		med("Rosuvastatina", lipid, no, "Oral", "10 a 20 mg una vez al día", "Tabletas 10 mg", "Tabletas 20 mg"),
		med("Simvastatina", lipid, no, "Oral", "20 a 40 mg por la noche", "Tabletas 20 mg", "Tabletas 40 mg"),
		med("Pravastatina", lipid, no, "Oral", "20 a 40 mg por la noche", "Tabletas 20 mg", "Tabletas 40 mg"),
		med("Ezetimiba", lipid, no, "Oral", "10 mg una vez al día", "Tabletas 10 mg"),
		med("Fenofibrato", lipid, no, "Oral", "160 a 200 mg una vez al día con alimentos", "Tabletas 160 mg", "Cápsulas 200 mg"),
		med("Bezafibrato", lipid, no, "Oral", "400 mg una vez al día (liberación prolongada)", "Tabletas 200 mg", "Tabletas 400 mg liberación prolongada"),
		med("Gemfibrozilo", lipid, no, "Oral", "600 mg cada 12 h antes de alimentos", "Tabletas 600 mg"),
		// Diabetes y endocrino
		med("Metformina", diab, no, "Oral", "500 a 850 mg cada 8-12 h con alimentos", "Tabletas 500 mg", "Tabletas 850 mg", "Tabletas 1000 mg"),
		med("Glibenclamida", diab, no, "Oral", "2.5 a 10 mg con el desayuno", "Tabletas 5 mg"),
		med("Glimepirida", diab, no, "Oral", "1 a 4 mg con el desayuno", "Tabletas 2 mg", "Tabletas 4 mg"),
		med("Sitagliptina", diab, no, "Oral", "100 mg una vez al día", "Tabletas 50 mg", "Tabletas 100 mg"),
		med("Linagliptina", diab, no, "Oral", "5 mg una vez al día", "Tabletas 5 mg"),
		med("Vildagliptina", diab, no, "Oral", "50 mg cada 12 h", "Tabletas 50 mg"),
		med("Dapagliflozina", diab, no, "Oral", "10 mg una vez al día", "Tabletas 10 mg"),
		med("Empagliflozina", diab, no, "Oral", "10 a 25 mg una vez al día", "Tabletas 10 mg", "Tabletas 25 mg"),
		med("Pioglitazona", diab, no, "Oral", "15 a 45 mg una vez al día", "Tabletas 15 mg", "Tabletas 30 mg"),
		med("Insulina NPH", diab, no, "Subcutánea", "Individualizada", "Frasco ámpula 100 UI/mL"),
		med("Insulina glargina", diab, no, "Subcutánea", "Individualizada, una vez al día", "Pluma 100 UI/mL"),
		med("Insulina humana regular", diab, no, "Subcutánea", "Individualizada antes de alimentos", "Frasco ámpula 100 UI/mL"),
		med("Levotiroxina", horm, no, "Oral", "1.6 mcg/kg/día; ajustar con TSH, en ayunas", "Tabletas 25 mcg", "Tabletas 50 mcg", "Tabletas 75 mcg", "Tabletas 100 mcg", "Tabletas 125 mcg", "Tabletas 150 mcg"),
		med("Metimazol", horm, no, "Oral", "5 a 30 mg/día", "Tabletas 5 mg", "Tabletas 10 mg"),
		med("Estradiol", horm, no, "Oral", "1 a 2 mg una vez al día", "Tabletas 1 mg", "Tabletas 2 mg"),
		med("Progesterona micronizada", horm, no, "Oral", "100 a 200 mg por la noche", "Cápsulas 100 mg", "Cápsulas 200 mg"),
		med("Medroxiprogesterona", horm, no, "Intramuscular", "150 mg cada 3 meses (anticoncepción)", "Suspensión inyectable 150 mg/mL"),
		med("Levonorgestrel", horm, no, "Oral", "1.5 mg dosis única, lo antes posible (anticoncepción de emergencia)", "Tabletas 1.5 mg"),
		med("Etinilestradiol / levonorgestrel", horm, no, "Oral", "1 tableta diaria por 21 días", "Tabletas 0.03 mg/0.15 mg"),
		med("Cabergolina", horm, no, "Oral", "0.25 a 1 mg dos veces por semana", "Tabletas 0.5 mg"),
		med("Clomifeno", horm, no, "Oral", "50 mg al día por 5 días", "Tabletas 50 mg"),
		med("Misoprostol", gi, no, "Oral", "200 mcg cada 6 h", "Tabletas 200 mcg").note("Contraindicado en embarazo."),
		med("Ácido tranexámico", horm, no, "Oral", "1 g cada 8 h durante la menstruación", "Tabletas 500 mg", "Ampolleta 500 mg/5 mL"),
		// Neurología y psiquiatría
		med("Clonazepam", psi, "Fracción III", "Oral", "0.5 a 2 mg al día", "Tabletas 0.5 mg", "Tabletas 2 mg", "Solución en gotas 2.5 mg/mL"),
		med("Alprazolam", psi, "Fracción III", "Oral", "0.25 a 0.5 mg cada 8 h", "Tabletas 0.25 mg", "Tabletas 0.5 mg", "Tabletas 1 mg"),
		med("Diazepam", psi, "Fracción III", "Oral", "2 a 10 mg cada 8-12 h", "Tabletas 5 mg", "Tabletas 10 mg", "Ampolleta 10 mg/2 mL"),
		med("Lorazepam", psi, "Fracción III", "Oral", "0.5 a 2 mg cada 8-12 h", "Tabletas 1 mg", "Tabletas 2 mg"),
		med("Bromazepam", psi, "Fracción III", "Oral", "1.5 a 3 mg cada 8-12 h", "Tabletas 3 mg"),
		med("Zolpidem", psi, "Fracción III", "Oral", "5 a 10 mg al acostarse", "Tabletas 10 mg"),
		med("Fenobarbital", neuro, "Fracción III", "Oral", "Individualizada", "Tabletas 100 mg"),
		med("Morfina", analg, "Fracción I o II", "Oral", "Requiere receta especial con código de barras", "Solución", "Ampolleta"),
		med("Fentanilo", analg, "Fracción I o II", "Intravenosa", "Requiere receta especial con código de barras", "Ampolleta", "Parche transdérmico"),
		med("Metilfenidato", psi, "Fracción I o II", "Oral", "Requiere receta especial con código de barras", "Tabletas 10 mg"),
		med("Sertralina", psi, no, "Oral", "50 a 200 mg una vez al día", "Tabletas 50 mg", "Tabletas 100 mg"),
		med("Fluoxetina", psi, no, "Oral", "20 a 40 mg por la mañana", "Cápsulas 20 mg", "Tabletas 20 mg"),
		med("Escitalopram", psi, no, "Oral", "10 a 20 mg una vez al día", "Tabletas 10 mg", "Tabletas 20 mg"),
		med("Paroxetina", psi, no, "Oral", "20 mg una vez al día", "Tabletas 20 mg"),
		med("Venlafaxina", psi, no, "Oral", "75 a 225 mg/día", "Cápsulas 75 mg liberación prolongada", "Cápsulas 150 mg liberación prolongada"),
		med("Duloxetina", psi, no, "Oral", "30 a 60 mg una vez al día", "Cápsulas 30 mg", "Cápsulas 60 mg"),
		med("Amitriptilina", psi, no, "Oral", "10 a 75 mg por la noche", "Tabletas 25 mg"),
		med("Mirtazapina", psi, no, "Oral", "15 a 45 mg por la noche", "Tabletas 15 mg", "Tabletas 30 mg"),
		med("Trazodona", psi, no, "Oral", "50 a 150 mg por la noche", "Tabletas 50 mg", "Tabletas 100 mg"),
		med("Buspirona", psi, no, "Oral", "10 mg cada 8-12 h", "Tabletas 10 mg"),
		med("Quetiapina", psi, no, "Oral", "25 a 800 mg/día según indicación", "Tabletas 25 mg", "Tabletas 100 mg", "Tabletas 200 mg"),
		med("Risperidona", psi, no, "Oral", "1 a 6 mg/día", "Tabletas 1 mg", "Tabletas 2 mg", "Tabletas 3 mg"),
		med("Olanzapina", psi, no, "Oral", "5 a 20 mg una vez al día", "Tabletas 5 mg", "Tabletas 10 mg"),
		med("Aripiprazol", psi, no, "Oral", "5 a 30 mg una vez al día", "Tabletas 5 mg", "Tabletas 10 mg", "Tabletas 15 mg"),
		med("Haloperidol", psi, no, "Oral", "0.5 a 5 mg cada 8-12 h", "Tabletas 5 mg", "Ampolleta 5 mg/mL"),
		med("Carbonato de litio", psi, no, "Oral", "Individualizada según litemia", "Tabletas 300 mg"),
		med("Carbamazepina", neuro, no, "Oral", "200 a 400 mg cada 8-12 h", "Tabletas 200 mg", "Suspensión 100 mg/5 mL"),
		med("Ácido valproico", neuro, no, "Oral", "250 a 500 mg cada 8-12 h", "Tabletas 250 mg", "Tabletas 500 mg", "Solución 250 mg/5 mL").note("Contraindicado en embarazo."),
		med("Lamotrigina", neuro, no, "Oral", "Titulación gradual; 100 a 400 mg/día", "Tabletas 25 mg", "Tabletas 100 mg"),
		med("Levetiracetam", neuro, no, "Oral", "500 a 1500 mg cada 12 h", "Tabletas 500 mg", "Tabletas 1000 mg", "Solución 100 mg/mL"),
		med("Fenitoína", neuro, no, "Oral", "300 a 400 mg/día", "Tabletas 100 mg", "Cápsulas 100 mg"),
		med("Topiramato", neuro, no, "Oral", "25 a 200 mg cada 12 h", "Tabletas 25 mg", "Tabletas 50 mg", "Tabletas 100 mg"),
		med("Gabapentina", neuro, no, "Oral", "300 a 600 mg cada 8 h", "Cápsulas 300 mg", "Tabletas 600 mg"),
		med("Pregabalina", neuro, no, "Oral", "75 a 150 mg cada 12 h", "Cápsulas 75 mg", "Cápsulas 150 mg"),
		med("Sumatriptán", neuro, no, "Oral", "50 a 100 mg al inicio de la crisis", "Tabletas 50 mg", "Tabletas 100 mg"),
		med("Rizatriptán", neuro, no, "Oral", "10 mg al inicio de la crisis", "Tabletas 10 mg"),
		med("Flunarizina", neuro, no, "Oral", "5 a 10 mg por la noche", "Tabletas 5 mg", "Tabletas 10 mg"),
		med("Betahistina", neuro, no, "Oral", "16 mg cada 8 h", "Tabletas 8 mg", "Tabletas 16 mg", "Tabletas 24 mg"),
		med("Piracetam", neuro, no, "Oral", "800 mg cada 8-12 h", "Tabletas 800 mg", "Tabletas 1200 mg"),
		med("Levodopa / carbidopa", neuro, no, "Oral", "Individualizada", "Tabletas 250/25 mg"),
		med("Donepezilo", neuro, no, "Oral", "5 a 10 mg por la noche", "Tabletas 5 mg", "Tabletas 10 mg"),
		med("Memantina", neuro, no, "Oral", "10 mg cada 12 h", "Tabletas 10 mg"),
		med("Melatonina", vit, no, "Oral", "3 mg por la noche", "Tabletas 3 mg"),
		// Musculoesquelético
		med("Ciclobenzaprina", musc, no, "Oral", "10 mg cada 8-12 h", "Tabletas 10 mg"),
		med("Metocarbamol", musc, no, "Oral", "500 a 1500 mg cada 6-8 h", "Tabletas 500 mg"),
		med("Tizanidina", musc, no, "Oral", "2 a 4 mg cada 8 h", "Tabletas 2 mg", "Tabletas 4 mg"),
		med("Baclofeno", musc, no, "Oral", "5 a 20 mg cada 8 h", "Tabletas 10 mg"),
		med("Colchicina", musc, no, "Oral", "0.5 mg cada 8-12 h", "Tabletas 0.5 mg"),
		med("Alopurinol", musc, no, "Oral", "100 a 300 mg una vez al día", "Tabletas 100 mg", "Tabletas 300 mg"),
		med("Febuxostat", musc, no, "Oral", "80 mg una vez al día", "Tabletas 80 mg"),
		// Urología
		med("Tamsulosina", uro, no, "Oral", "0.4 mg una vez al día", "Cápsulas 0.4 mg"),
		med("Finasterida", uro, no, "Oral", "5 mg una vez al día", "Tabletas 5 mg"),
		med("Sildenafil", uro, no, "Oral", "50 mg una hora antes de la actividad sexual", "Tabletas 50 mg", "Tabletas 100 mg"),
		med("Tadalafilo", uro, no, "Oral", "5 mg diarios o 20 mg a demanda", "Tabletas 5 mg", "Tabletas 20 mg"),
		med("Oxibutinina", uro, no, "Oral", "5 mg cada 8-12 h", "Tabletas 5 mg"),
		med("Solifenacina", uro, no, "Oral", "5 a 10 mg una vez al día", "Tabletas 5 mg", "Tabletas 10 mg"),
		med("Fenazopiridina", uro, no, "Oral", "200 mg cada 8 h por máximo 2 días", "Tabletas 100 mg", "Tabletas 200 mg"),
		// Vitaminas y suplementos
		med("Ácido fólico", vit, no, "Oral", "5 mg al día (400 mcg en prevención)", "Tabletas 5 mg", "Tabletas 400 mcg"),
		med("Sulfato ferroso", vit, no, "Oral", "65 mg de hierro elemental cada 8-24 h", "Tabletas 200 mg (65 mg de hierro)", "Solución 125 mg/mL").kg(3, 6),
		med("Colecalciferol (vitamina D3)", vit, no, "Oral", "1000 a 4000 UI al día", "Gotas 400 UI/gota", "Cápsulas 1000 UI", "Cápsulas 5000 UI"),
		med("Cianocobalamina (vitamina B12)", vit, no, "Intramuscular", "1000 mcg cada semana o cada mes", "Ampolleta 1000 mcg", "Tabletas 1000 mcg"),
		med("Tiamina / piridoxina / cianocobalamina", vit, no, "Oral", "1 a 2 tabletas al día", "Tabletas", "Ampolleta"),
		med("Ácido ascórbico (vitamina C)", vit, no, "Oral", "500 mg al día", "Tabletas 500 mg"),
		med("Calcio / vitamina D", vit, no, "Oral", "600 mg/400 UI cada 12 h", "Tabletas 600 mg/400 UI"),
		med("Zinc", vit, no, "Oral", "10 a 20 mg al día", "Tabletas 20 mg", "Solución"),
		med("Omega 3", vit, no, "Oral", "1 g al día", "Cápsulas 1 g"),
		// Dermatología y tópicos
		med("Ácido fusídico", topic, no, "Tópica", "Aplicar 3 veces al día", "Crema 2%", "Ungüento 2%"),
		med("Mupirocina", topic, no, "Tópica", "Aplicar 3 veces al día por 5-10 días", "Ungüento 2%"),
		med("Sulfadiazina de plata", topic, no, "Tópica", "Aplicar 1-2 veces al día en quemaduras", "Crema 1%"),
		med("Tretinoína", topic, no, "Tópica", "Aplicar por la noche", "Crema 0.025%", "Crema 0.05%", "Gel 0.025%"),
		med("Adapaleno", topic, no, "Tópica", "Aplicar por la noche", "Gel 0.1%"),
		med("Peróxido de benzoílo", topic, no, "Tópica", "Aplicar 1-2 veces al día", "Gel 5%"),
		med("Clindamicina tópica", topic, no, "Tópica", "Aplicar 2 veces al día", "Gel 1%", "Solución 1%"),
		med("Isotretinoína", topic, no, "Oral", "0.5 a 1 mg/kg/día", "Cápsulas 20 mg").note("Teratogénica: requiere anticoncepción y seguimiento."),
		med("Minoxidil", topic, no, "Tópica", "1 mL dos veces al día", "Solución 2%", "Solución 5%"),
		med("Urea", topic, no, "Tópica", "Aplicar 1-2 veces al día", "Crema 10%", "Crema 20%"),
		med("Calamina", topic, no, "Tópica", "Aplicar según necesidad", "Loción"),
		med("Diclofenaco tópico", aine, no, "Tópica", "Aplicar 3-4 veces al día", "Gel 1%"),
		med("Povidona yodada", topic, no, "Tópica", "Aplicar en la zona según necesidad", "Solución 10%"),
		// Oftalmología y otología
		med("Tobramicina oftálmica", oft, no, "Oftálmica", "1-2 gotas cada 4-6 h", "Solución oftálmica 0.3%"),
		med("Tobramicina / dexametasona oftálmica", oft, no, "Oftálmica", "1-2 gotas cada 6 h", "Solución oftálmica 0.3%/0.1%", "Ungüento oftálmico"),
		med("Ciprofloxacino oftálmico", oft, no, "Oftálmica", "1-2 gotas cada 4-6 h", "Solución oftálmica 0.3%"),
		med("Carboximetilcelulosa", oft, no, "Oftálmica", "1-2 gotas según necesidad", "Solución oftálmica 0.5%"),
		med("Olopatadina", oft, no, "Oftálmica", "1 gota cada 12 h", "Solución oftálmica 0.1%"),
		med("Timolol oftálmico", oft, no, "Oftálmica", "1 gota cada 12 h", "Solución oftálmica 0.5%"),
		med("Latanoprost", oft, no, "Oftálmica", "1 gota por la noche", "Solución oftálmica 0.005%"),
		med("Ciprofloxacino ótico", oto, no, "Ótica", "3-4 gotas cada 12 h", "Solución ótica 0.3%"),
		med("Neomicina / polimixina / hidrocortisona ótica", oto, no, "Ótica", "3-4 gotas cada 6-8 h", "Solución ótica"),
		// Anestésicos y odontología
		med("Lidocaína", anest, no, "Tópica", "Aplicar según necesidad", "Gel 2%", "Spray 10%", "Solución inyectable 2%"),
		med("Lidocaína con epinefrina", anest, no, "Otra", "Infiltración según procedimiento", "Cartucho dental 2% con epinefrina 1:100,000", "Solución inyectable 2% con epinefrina"),
		med("Bupivacaína", anest, no, "Otra", "Infiltración según procedimiento", "Solución inyectable 0.5%"),
		med("Articaína con epinefrina", anest, no, "Otra", "Infiltración dental", "Cartucho dental 4% con epinefrina 1:100,000"),
		med("Clorhexidina", topic, no, "Tópica", "Enjuagar 15 mL por 30 s cada 12 h", "Colutorio 0.12%"),
	}
}
