name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  vercel:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: team_zTGwYKWZiYNP6cXzPReKRjpF
      VERCEL_PROJECT_ID: prj_QlRAHPaibDuo2UVqYW27cOqkrGK7
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: npm install --global vercel@latest
      - run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN
      - run: vercel build --prod --token=$VERCEL_TOKEN
      - run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
